name: Mind Grapher
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  daily_and_visual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate new file
        run: |
          cp ${GITHUB_WORKSPACE}/daily/sample.md ${GITHUB_WORKSPACE}/daily/$(date -u '+%Y-%m-%d').md
          
      - name: Calculate and record
        run: |
          previous_date=$(date -d "yesterday" +%Y-%m-%d)
          checked_count=$(grep -oP '\[x\]' "${GITHUB_WORKSPACE}/daily/$previous_date.md" | wc -l)
          echo "$previous_date: $checked_count" >> "${GITHUB_WORKSPACE}/record_list.txt"
          star_icons=$(printf '⭐️%.0s' $(seq 1 $checked_count))
          awk -v stars="$star_icons" '/^# How are you doing today\?$/ {print; print stars; next} 1' "${GITHUB_WORKSPACE}/daily/$previous_date.md" > "temp.md" && mv "temp.md" "${GITHUB_WORKSPACE}/daily/$previous_date.md"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install matplotlib

      - name: Generate chart
        run: python generate_chart.py

      - name: Commit chart
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update mind grapher daily"
          git push   
