name: Mind Grapher
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate new file
        run: |
          cp ${GITHUB_WORKSPACE}/daily/sample.md ${GITHUB_WORKSPACE}/daily/$(date -u '+%Y-%m-%d').md
          ls -al ${GITHUB_WORKSPACE}/daily
          
      - name: Calculate previous day's data
        run: |
          previous_date=$(date -d "yesterday" +%Y-%m-%d)
          checked_count=$(grep -oP '\[x\]' "${GITHUB_WORKSPACE}/daily/$previous_date.md" | wc -l)
          star_icons=$(printf '⭐️%.0s' $(seq 1 $checked_count))
          awk -v stars="$star_icons" '/^# How are you doing today\?$/ {print; print stars; next} 1' "${GITHUB_WORKSPACE}/daily/$previous_date.md" > "temp.md" && mv "temp.md" "${GITHUB_WORKSPACE}/daily/$previous_date.md"

      - name: Update record list
        run: |
          previous_date=$(date -d "yesterday" +%Y-%m-%d)
          echo "$previous_date: $(grep -oP '\[x\]' "${GITHUB_WORKSPACE}/daily/$previous_date.md" | wc -l)" >> "${GITHUB_WORKSPACE}/record_list.txt"

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install matplotlib

      - name: Generate chart
        run: python generate_chart.py

      - name: Commit chart
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add mind-grapher.png
          git commit -m "Update mind grapher"
          git push   
